import { getCollection, render } from "astro:content";
import careerImages from "../../../../data/career-images.json";
import {
  compareCareerEntries,
  createCareerEntryViewModel,
  type CareerEntry,
  type CareerEntryViewModel,
  type CareerImageMap,
} from "./career-view-model";

// SAFETY: career-images.json is generated by scripts/sync-site-image-metadata
// with exactly this shape; the cast names it, and a missing `images` key
// degrades to an empty map rather than a crash.
const careerImageMap =
  (
    careerImages as {
      images?: CareerImageMap;
    }
  ).images ?? {};

export async function loadCareerEntries(): Promise<CareerEntryViewModel[]> {
  const careerCollection = (await getCollection("career")).toSorted(compareCareerEntries);

  return Promise.all(
    careerCollection.map(async (entry: CareerEntry) => {
      const { Content } = await render(entry);

      return createCareerEntryViewModel(entry, Content, careerImageMap);
    }),
  );
}

/**
 * Look up one entry by slug for authorial (prose-order) use, failing the
 * static build loudly on a typo instead of rendering a hole.
 */
export function requireCareerEntry(
  entries: readonly CareerEntryViewModel[],
  slug: string,
): CareerEntryViewModel {
  const entry = entries.find((candidate) => candidate.slug === slug);

  if (!entry) {
    throw new Error(`Unknown career entry slug: ${slug}`);
  }

  return entry;
}
